coverage:
  dockerfile: docker/Dockerfile.coverage
  build: .

test:
  build: .
  dockerfile: docker/Dockerfile.test
  environment:
    NODE_ENV: test
  volumes_from:
    - coverage
  volumes:
    - "./.git:/usr/src/app/.git"
