version: '2.1'

services:

  coverage:
    build:
      context: .
      dockerfile: docker/Dockerfile.coverage

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    volumes_from:
      - coverage
    env_file:
      - ./.env.test
