coverage:
  dockerfile: docker/Dockerfile.coverage
  build: .

test:
  build: .
  dockerfile: docker/Dockerfile.test
  volumes_from:
    - coverage
  volumes:
    - "./.git:/usr/src/app/.git"
  env_file:
    - ./.env.test
